### ISSUE TITLE
Addon icon about loop don't follow changes from other places

### ISSUE THREAD

**Issue by krystian3w** [Dosx001/YouTubeUtils#2]
The icon for looping playback does not work with the native HTML5 or browser context menu option.

It gets to the point where I have activated a loop from there and the add-on icon does not detect the change.

<details> <summary> screenshots </summary>

![obraz](https://github.com/Dosx001/YouTubeUtils/assets/35370833/7ac8d9c7-abf3-49d8-9a88-ce516507f3c6) | ![obraz](https://github.com/Dosx001/YouTubeUtils/assets/35370833/7b0d8db8-91fc-4bd9-8677-9cb381f506be)
--- | ---
HTML5 interface | browser interface

</details> 

Maybe possible rewrite icon background to CSS4 (Firefox 121+ - Based on the bugzilla, there is no indication that the release will be delayed for a 122nd release or a gradual unlocking over several releases)?

```css
#movie_player:has(video.video-stream.html5-main-video:not([loop=""])) div ~ 
    div #ytutils-loop svg path:first-child { 
            display: none
}

#movie_player:has(video.video-stream.html5-main-video[loop=""]) div ~ 
    div #ytutils-loop svg path:first-child {
            display: block !important
}

```

Firefox older than 116 would still require some kind of [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver).
